### ISSUE TITLE
No file created issue

### ISSUE THREAD

**Issue by AhmedGsm** [htmlfactorycz/grunt-img-to-inlinesvg#1]
I tried the configuration that you made but it don't work:
`grunt.initConfig({
  img_to_inlinesvg: {
    options: {
      svgFileLimit: 10,
      assetsDir: "",
      selector: "img[inline]"
    },
    files: {
      'dest/index.html': ['src/index.html'],
    },
  },
});`
THE GOOD CONFIGURATION THAT WORKED FOR ME IS:

`img_to_inlinesvg: {

      main: {

        options: {

          svgFileLimit: 10000000, // BE CAREFUL choose the right max svg inline file

          assetsDir: "images/", // svg Images directory

          selector: "img[src]" // This will convert all <img elements that contains svg resource files. If you want to select a customs 
`// <img elements, then add inline attribute to the images element (<img inline src="..."  `
class="....".../>) and set **selector**: "img[_inline_]" 

        },

        files: {

          'index_inlineSvg.html': ['index.html'], // Destination file name :  Source file name

        },

      }

    },`

**Comment by vitaly-petras** [comment]
Hi Ahmed, i use this plugin on daily basis and it works. I also tested it on empty grunt projekt and it also worked. So i think you just missed some configuration (like wrong path, or large svg image for example). So i am closing this issue, because it looks like you found solution yourself.

PS - you have too large svg file size limit. The reason of this plugin to replace some very simple svg icons, not to replace all svg files that can be too large and too complicated.

**Comment by vitaly-petras** [comment]
I also looks on your post, and it looks like you changing the main plugin cofiguration, but you should configure it in your custom project gruntfile. This is my settings for example:
```
img_to_inlinesvg: {
    options: {
      svgFileLimit: 10,
      assetsDir: "dist",
    },
    all: {
      cwd: `${path.public}`,
      src: ["**/*.{html,php}", "!components/**"],
      dest: `${path.public}`,
      expand: true
    }
  },
```
